apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
  labels:
    app: login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
        type: api-server
    spec:
      containers:
      - name: login
        image: vikcoc/platform_thingie:sha-9244c51
        ports:
        - containerPort: 80
        name: login-port

---
apiVersion: v1
kind: Service
metadata:
  name: platform-thingie-login-service
spec:
  type: NodePort
  selector:
    app: login # Use labels to select pods running your application
    type: api-server
  ports:
    - protocol: TCP # Or UDP depending on your service
      port: 30001 # Internal port exposed by your application
      targetPort: 80 # Port on which pods listen
      nodePort: 30001 # Leave blank for automatic assignment
