apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-db-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /k8volumes2/app-db-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {InsertNodeNameHere}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: Pod
metadata:
    name: app-db-pod
    labels:
        app: app-db-label
        type: database
spec:
    containers:
    - name: app-db-container
      image: postgres:16.2-bookworm
      ports:
      - containerPort: 5432
      volumeMounts:
      - name: database-volume
        mountPath: /var/lib/postgresql/data
      envFrom:
      - secretRef:
          name: db-secret
    volumes:
    - name: database-volume
      persistentVolumeClaim:
        claimName: app-db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
  labels:
    app: login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
        type: api-server
    spec:
      containers:
      - name: login
        image: vikcoc/auth_platform:sha-90ce07c
        ports:
        - containerPort: 80
        name: login-port
        volumeMounts:
          - name: application-secrets
            mountPath: /app/conf
      volumes:
      - name: application-secrets
        secret:
          secretName: config-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-deployment
  labels:
    app: public
spec:
  replicas: 2
  selector:
    matchLabels:
      app: public
  template:
    metadata:
      labels:
        app: public
        type: api-server
    spec:
      containers:
      - name: public
        image: vikcoc/public_platform:sha-90ce07c
        ports:
        - containerPort: 80
        name: public-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
        type: api-server
    spec:
      containers:
      - name: user
        image: vikcoc/user_platform:sha-90ce07c
        ports:
        - containerPort: 80
        name: user-port
        volumeMounts:
          - name: user-secrets
            mountPath: /app/conf
      volumes:
      - name: user-secrets
        secret:
          secretName: user-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
        type: api-server
    spec:
      containers:
      - name: inventory
        image: vikcoc/inventory_platform:sha-90ce07c
        ports:
        - containerPort: 80
        name: inventory-port
        volumeMounts:
          - name: inventory-secrets
            mountPath: /app/conf
      volumes:
      - name: user-secrets
        secret:
          secretName: user-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: migration-pod
spec:
  containers:
  - name: migration
    image: vikcoc/migration_platform:sha-90ce07c
    volumeMounts:
    - name: database-secrets
      mountPath: /app/conf
  restartPolicy: Never
  volumes:
  - name: database-secrets
    secret:
      secretName: migration-secret

---
kind: Service
apiVersion: v1
metadata:
  name: app-db-service
spec:
  ports:
    - port: 30010
      targetPort: 5432
      protocol: TCP
  selector:
    app: app-db-label
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: platform-thingie-login-service
spec:
  type: NodePort
  selector:
    app: login
    type: api-server
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 80
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: platform-thingie-public-service
spec:
  type: NodePort
  selector:
    app: public
    type: api-server
  ports:
    - protocol: TCP
      port: 30002
      targetPort: 80
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: platform-thingie-user-service
spec:
  type: NodePort
  selector:
    app: user
    type: api-server
  ports:
    - protocol: TCP
      port: 30003
      targetPort: 80
      nodePort: 30003