apiVersion: v1
kind: Secret
metadata:
  name: migration-secret
data:
  config.json: someBase64
---
apiVersion: v1
kind: Secret
metadata:
  name: config-secret
data:
  appsettings.Production.json: someBase64
---
