// <auto-generated />
using InvTemplateDbComponent.entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvTemplateDbComponent.Migrations
{
    [DbContext(typeof(InvTemplateContext))]
    partial class InvTemplateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvTemplateDbComponent.entities.InvTemplate", b =>
                {
                    b.Property<string>("InvTemplateName")
                        .HasColumnType("text");

                    b.Property<long>("InvTemplateVersion")
                        .HasColumnType("bigint");

                    b.Property<bool>("Released")
                        .HasColumnType("boolean");

                    b.HasKey("InvTemplateName", "InvTemplateVersion");

                    b.ToTable("InvTemplates");
                });

            modelBuilder.Entity("InvTemplateDbComponent.entities.InvTemplateAttr", b =>
                {
                    b.Property<string>("InvTemplateName")
                        .HasColumnType("text");

                    b.Property<long>("InvTemplateVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("InvTemplateAttrName")
                        .HasColumnType("text");

                    b.Property<string>("InvTemplateAttrAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvTemplateAttrValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InvTemplateName", "InvTemplateVersion", "InvTemplateAttrName");

                    b.ToTable("InvTemplatesAttrs");
                });

            modelBuilder.Entity("InvTemplateDbComponent.entities.InvTemplateAttrPermission", b =>
                {
                    b.Property<string>("InvTemplateName")
                        .HasColumnType("text");

                    b.Property<long>("InvTemplateVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("InvTemplateAttrName")
                        .HasColumnType("text");

                    b.Property<string>("InvTemplatePermissionName")
                        .HasColumnType("text");

                    b.HasKey("InvTemplateName", "InvTemplateVersion", "InvTemplateAttrName", "InvTemplatePermissionName");

                    b.HasIndex("InvTemplatePermissionName");

                    b.ToTable("InvTemplatesAttrPermissions");
                });

            modelBuilder.Entity("InvTemplateDbComponent.entities.InvTemplateEntAttr", b =>
                {
                    b.Property<string>("InvTemplateName")
                        .HasColumnType("text");

                    b.Property<long>("InvTemplateVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("InvTemplateEntAttrName")
                        .HasColumnType("text");

                    b.Property<string>("InvTemplateEntAttrAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InvTemplateName", "InvTemplateVersion", "InvTemplateEntAttrName");

                    b.ToTable("InvTemplateEntAttrs");
                });

            modelBuilder.Entity("InvTemplateDbComponent.entities.InvTemplateEntAttrPermission", b =>
                {
                    b.Property<string>("InvTemplateName")
                        .HasColumnType("text");

                    b.Property<long>("InvTemplateVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("InvTemplateEntAttrName")
                        .HasColumnType("text");

                    b.Property<string>("InvTemplatePermissionName")
                        .HasColumnType("text");

                    b.Property<bool>("Writeable")
                        .HasColumnType("boolean");

                    b.HasKey("InvTemplateName", "InvTemplateVersion", "InvTemplateEntAttrName", "InvTemplatePermissionName");

                    b.HasIndex("InvTemplatePermissionName");

                    b.ToTable("InvTemplateEntAttrPermissions");
                });

            modelBuilder.Entity("InvTemplateDbComponent.entities.InvTemplatePermission", b =>
                {
                    b.Property<string>("InvTemplatePermissionName")
                        .HasColumnType("text");

                    b.HasKey("InvTemplatePermissionName");

                    b.ToTable("InvTemplatePermissions");
                });

            modelBuilder.Entity("InvTemplateDbComponent.entities.InvTemplateAttr", b =>
                {
                    b.HasOne("InvTemplateDbComponent.entities.InvTemplate", "InvTemplate")
                        .WithMany("InvTemplateAttr")
                        .HasForeignKey("InvTemplateName", "InvTemplateVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvTemplate");
                });

            modelBuilder.Entity("InvTemplateDbComponent.entities.InvTemplateAttrPermission", b =>
                {
                    b.HasOne("InvTemplateDbComponent.entities.InvTemplatePermission", "InvTemplatePermission")
                        .WithMany("InvTemplateAttrPermissions")
                        .HasForeignKey("InvTemplatePermissionName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvTemplateDbComponent.entities.InvTemplateAttr", "InvTemplateAttr")
                        .WithMany("InvTemplateAttrPermissions")
                        .HasForeignKey("InvTemplateName", "InvTemplateVersion", "InvTemplateAttrName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvTemplateAttr");

                    b.Navigation("InvTemplatePermission");
                });

            modelBuilder.Entity("InvTemplateDbComponent.entities.InvTemplateEntAttr", b =>
                {
                    b.HasOne("InvTemplateDbComponent.entities.InvTemplate", "InvTemplate")
                        .WithMany("InvTemplateEntAttr")
                        .HasForeignKey("InvTemplateName", "InvTemplateVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvTemplate");
                });

            modelBuilder.Entity("InvTemplateDbComponent.entities.InvTemplateEntAttrPermission", b =>
                {
                    b.HasOne("InvTemplateDbComponent.entities.InvTemplatePermission", "InvTemplatePermission")
                        .WithMany("InvTemplateEntAttrPermissions")
                        .HasForeignKey("InvTemplatePermissionName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvTemplateDbComponent.entities.InvTemplateEntAttr", "InvTemplateEntAttr")
                        .WithMany("InvTemplateEntAttrPermissions")
                        .HasForeignKey("InvTemplateName", "InvTemplateVersion", "InvTemplateEntAttrName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvTemplateEntAttr");

                    b.Navigation("InvTemplatePermission");
                });

            modelBuilder.Entity("InvTemplateDbComponent.entities.InvTemplate", b =>
                {
                    b.Navigation("InvTemplateAttr");

                    b.Navigation("InvTemplateEntAttr");
                });

            modelBuilder.Entity("InvTemplateDbComponent.entities.InvTemplateAttr", b =>
                {
                    b.Navigation("InvTemplateAttrPermissions");
                });

            modelBuilder.Entity("InvTemplateDbComponent.entities.InvTemplateEntAttr", b =>
                {
                    b.Navigation("InvTemplateEntAttrPermissions");
                });

            modelBuilder.Entity("InvTemplateDbComponent.entities.InvTemplatePermission", b =>
                {
                    b.Navigation("InvTemplateAttrPermissions");

                    b.Navigation("InvTemplateEntAttrPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
