# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: See location
      run: pwd
    - name: See contents
      run: ls -R
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: PlatformThingie
        path: PlatformThingie
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download build
      uses: actions/download-artifact@v4
      with:
        name: PlatformThingie
    - name: Test download
      run: ls -R
    - name: Test
      run: dotnet test --no-build --verbosity normal
